<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>glCloseBtnPopup</name>
   <tag></tag>
   <elementGuidId>41eaabd3-7bb6-45f3-8f81-cdd44d4f31f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.close-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class='close-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6efbaed3-062d-40f8-8903-33a7994c1a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-button</value>
      <webElementGuid>e3a9be8c-34cc-4c2d-b76e-5524e4f2921e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/one/images/ic-close-rounded.svg</value>
      <webElementGuid>8b69b4a6-e11f-45b5-b2e7-6e85c0c1a157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24px</value>
      <webElementGuid>baa2ed7e-2d76-4c25-baf6-9c42b0f9367b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24px</value>
      <webElementGuid>e245ec01-4052-43af-864f-dc29d20222e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>0cbbf6c9-c144-4137-958d-108ab724a65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;banner&quot;]/div[@class=&quot;popup-container&quot;]/img[@class=&quot;close-button&quot;]</value>
      <webElementGuid>49e54222-d2e6-4d77-a115-39506e1f0c1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[5]/div/img</value>
      <webElementGuid>152ffb86-8906-4fdc-9d08-22a7b29050e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='close']</value>
      <webElementGuid>9810cf42-ecd7-4b74-a253-017d1f6c7e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/img</value>
      <webElementGuid>605bdbc5-65ec-4b59-a4ed-92a17ae4a342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/one/images/ic-close-rounded.svg' and @title = 'close']</value>
      <webElementGuid>374fb7a9-26c9-4eda-8739-9a18c1687459</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
