<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>glDashboardTitle</name>
   <tag></tag>
   <elementGuidId>d19bb31c-0b68-43da-b003-f8b33f6268fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[title=&quot;Testing Accounting V2 (Aris PKP)&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href='/dashboard']//img[@title='Testing Accounting V2 (Aris PKP)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>949585bd-179c-424d-9125-9dba4c5bc6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/uploads/images/96111-stl226462.jpg</value>
      <webElementGuid>7f58e0cc-4223-4b46-8f7a-23a3a0301996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>4e41fac5-a5af-4b68-8744-3db81a94933e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Testing Accounting V2 (Aris PKP)</value>
      <webElementGuid>d1e36c0a-da57-4e23-8359-edebebbae764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;slim-header&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;slim-header-left&quot;]/h2[@class=&quot;slim-logo&quot;]/a[1]/img[1]</value>
      <webElementGuid>be082d96-d555-4718-b497-cb4d01f97aca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/h2/a/img</value>
      <webElementGuid>8d64d71c-06ef-42d5-922d-9128215d9f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Testing Accounting V2 (Aris PKP)']</value>
      <webElementGuid>8eacad87-05ea-4b67-998e-5ce05e94d1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>fd324293-7538-40f0-997d-af05538feb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/uploads/images/96111-stl226462.jpg' and @title = 'Testing Accounting V2 (Aris PKP)']</value>
      <webElementGuid>8413bcd7-bf56-4f15-820a-21242e2d0a61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
