<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>glListItemPenjualan</name>
   <tag></tag>
   <elementGuidId>153793fd-7fd9-4021-9f66-1f985964a89a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='pos-list']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pos-list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4e81d863-35fa-4368-8320-6777efc07a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pos-list</value>
      <webElementGuid>70c0faf4-036b-4a15-893e-f0605e5e7986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[CTRL+ALT+L]Item NameQtyUnitTuslahPriceDiscountSub TotalNR AMOXICILLIN IFARS 500 MG BOX 10 STR @ 10 TABTAB0600600</value>
      <webElementGuid>0df5b699-20eb-4b94-9f78-a8a320cd40c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;pos-list&quot;]</value>
      <webElementGuid>9b706368-755b-4aee-a3c7-4a26522ad909</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[4]/div[2]</value>
      <webElementGuid>81272cf8-b5b2-429d-8090-53071932bee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Total'])[1]/following::div[3]</value>
      <webElementGuid>e4a8e408-12af-43ec-9464-750d581235b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discount'])[1]/following::div[5]</value>
      <webElementGuid>135c4d06-1e3c-4522-857a-8585a20c1145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>461654c3-2d34-4402-88c6-c0943c985e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '[CTRL+ALT+L]Item NameQtyUnitTuslahPriceDiscountSub TotalNR AMOXICILLIN IFARS 500 MG BOX 10 STR @ 10 TABTAB0600600' or . = '[CTRL+ALT+L]Item NameQtyUnitTuslahPriceDiscountSub TotalNR AMOXICILLIN IFARS 500 MG BOX 10 STR @ 10 TABTAB0600600')]</value>
      <webElementGuid>460a39fe-e808-477e-be3f-bb7d54797a5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
