<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>glPOSDashboard</name>
   <tag></tag>
   <elementGuidId>aad3eb9b-e065-48af-a77a-c5315d4937ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href='/dashboard' or @class='fa fa-home']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ba7e515c-f8ec-444f-bafd-7b769f7ed9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tx-bold</value>
      <webElementGuid>040fb173-1454-42ce-81de-5f8a1090d797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testing Accounting V2 (Aris PKP)</value>
      <webElementGuid>1328a155-5707-4550-a7cf-283aa604e179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row pd-t-5 m-ht-30 mg-b-10 tx-white bg-grandeur&quot;]/div[@class=&quot;col-md-5&quot;]/span[@class=&quot;tx-bold&quot;]</value>
      <webElementGuid>7f00c17b-c420-418d-80d3-fe3e6bf2f840</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/span[2]</value>
      <webElementGuid>d0de5cf3-c56d-4b5b-a311-34e8cfd11e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::span[1]</value>
      <webElementGuid>0e156d52-46fe-4e96-9511-f75b59a933af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::span[1]</value>
      <webElementGuid>6d712b3c-8c21-40ff-aa3c-2bf98491b394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestingPKP'])[1]/preceding::span[2]</value>
      <webElementGuid>c5cb0e2f-0f37-4a07-bc1a-b3b1a0b452c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Testing Accounting V2 (Aris PKP)']/parent::*</value>
      <webElementGuid>ece0d8ed-af3a-4939-8f45-0fb50978b439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>c0922faa-0263-4a48-9ac3-6d691dcb43f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Testing Accounting V2 (Aris PKP)' or . = 'Testing Accounting V2 (Aris PKP)')]</value>
      <webElementGuid>0821075d-ce31-41a5-bb24-8d40a1fbebcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
