<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>glResepBtn</name>
   <tag></tag>
   <elementGuidId>65d1d10d-8147-41ba-b70d-dfde3bad42a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@data-vbtype='iframe' and @title='Search Prescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-sm.btn-warning.venobox-rs.vbox-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>78c4346f-7a8d-45da-8b36-8adfbdd23af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-warning venobox-rs vbox-item</value>
      <webElementGuid>f510e4d5-21c8-4095-9253-b583ffb46d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vbtype</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>019a7feb-1430-4ca2-8d54-ac570e272d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/prescription-iframe/?iframe=pos&amp;input=item_name</value>
      <webElementGuid>72bde6fc-15b7-404b-95ac-02a79acb52df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search Prescription</value>
      <webElementGuid>e4d1d8dd-105e-4bb2-8f1f-90d65d8d1cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form-layout form-layout-2&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;input-group-append&quot;]/a[@class=&quot;btn btn-sm btn-warning venobox-rs vbox-item&quot;]</value>
      <webElementGuid>01123f89-fb1c-4622-b3dd-e0a0c60d8429</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[4]/div/div/div/div/div/div/a</value>
      <webElementGuid>d9689907-7a9b-42c4-93f7-1f9b779b1dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PLU / Barcode'])[1]/following::a[1]</value>
      <webElementGuid>beff3946-1aca-45d3-9163-6ff77491cdc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tuslah'])[1]/preceding::a[1]</value>
      <webElementGuid>077bf85c-cc3d-4dc6-bfd5-911a16622481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/preceding::a[1]</value>
      <webElementGuid>7db35998-6146-489d-a695-66a79e9c7906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/prescription-iframe/?iframe=pos&amp;input=item_name')]</value>
      <webElementGuid>37855916-fa65-4e5e-a83b-10614a4c58b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/a</value>
      <webElementGuid>446902f7-eb6e-4f05-9c2e-dbd7c89e9bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/prescription-iframe/?iframe=pos&amp;input=item_name' and @title = 'Search Prescription']</value>
      <webElementGuid>711fada6-f3cf-497b-a252-4a2d12a0f77c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
