<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>glBtnSelectedItem</name>
   <tag></tag>
   <elementGuidId>6e3d8d63-9f00-45ea-8015-0c5e6fa6704c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class='btn btn-sm btn-primary btn-insert' and contains(@data-name,'${item}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-sm.btn-primary.btn-insert</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>08c5b541-63e5-49d7-9361-f65551973b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>e4b203fe-661d-4a2d-a564-c8255fe4a9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>294294</value>
      <webElementGuid>d2c5e17a-2686-4fc9-9501-fbc8edceb35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-code</name>
      <type>Main</type>
      <value>10521</value>
      <webElementGuid>40311e76-4a86-4a20-90dd-f18dc57dcd50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>AMOXICILLIN IFARS 500 MG BOX 10 STR @ 10 TAB</value>
      <webElementGuid>5fd522a2-3e76-4bf4-856e-48e7a9a62de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-description</name>
      <type>Main</type>
      <value>AMOXICILLIN IFARS 500 MG BOX 10 STR @ 10 TAB</value>
      <webElementGuid>fe13f309-1da0-4676-8ab9-4f24a17bf60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-stock</name>
      <type>Main</type>
      <value>12318</value>
      <webElementGuid>2b0d461b-45a3-4372-8396-fd2b3679c582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-punit</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>d6c4498e-7098-42aa-b136-1408f7820f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unit</name>
      <type>Main</type>
      <value>26</value>
      <webElementGuid>1ac13321-8473-472b-b6da-674ca9172795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-unit</name>
      <type>Main</type>
      <value>26</value>
      <webElementGuid>455bb247-b419-4686-ab00-82e0c6e93a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unit-code</name>
      <type>Main</type>
      <value>TAB</value>
      <webElementGuid>63764983-41e5-4c27-bbc9-c7fb49e44c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unitconv</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>ca958b8d-25ff-4db8-bf4c-a34eafb60d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-conv</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>70a65c9f-6857-4ceb-8327-f9d0ef49dcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tax</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a3c6847e-b9a2-422b-9a48-2b634adf05f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tax-amount</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>587520cd-7d54-4396-b9c7-557d6cfc2396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>50000</value>
      <webElementGuid>0ad1d192-b3e2-40bd-8a76-2a1e5e8794e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sprice</name>
      <type>Main</type>
      <value>60000</value>
      <webElementGuid>a0efbdad-a2b5-4ab2-8560-10788b2738ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sdiscount</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>77cee8cf-3fe8-47bd-b7a6-89dd5ae09ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isfixed</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cb3ca192-91ce-468e-a609-2aa5b4be683a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isbatch</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>de51c17a-1e01-4bc3-b067-c0c6144d7dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-iscons</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c6d4d881-676c-4517-b3a1-5c0219f7cc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>d8fa5cc1-a510-4f93-a88f-8804e783e5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sizeunit</name>
      <type>Main</type>
      <value>MG</value>
      <webElementGuid>9ecec150-6450-4220-ae82-1db210c894ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b2d64229-6394-466d-bcef-0fad5da4f6b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary btn-insert</value>
      <webElementGuid>a73bf707-0662-484b-9894-b66f274a8c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Insert</value>
      <webElementGuid>bb3ad130-b9b8-47d6-8cf1-7c7f5a317652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-item-modal-pos&quot;)/tbody[@class=&quot;table-body&quot;]/tr[@class=&quot;odd&quot;]/td[1]/div[@class=&quot;text-center&quot;]/div[@class=&quot;btn-group btn-group-sm&quot;]/a[@class=&quot;btn btn-sm btn-primary btn-insert&quot;]</value>
      <webElementGuid>caaa6377-d168-4b7c-a4e2-168d7a4018cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-item-modal-pos']/tbody/tr/td/div/div/a</value>
      <webElementGuid>19b25faa-8384-4fa8-9ba5-5469e26de073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::a[1]</value>
      <webElementGuid>9f574a44-2d85-4526-9cb2-a3bdcc076621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consign.'])[1]/following::a[1]</value>
      <webElementGuid>a9e5ba93-c188-4b80-9740-fd81f32c0310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventory'])[2]/preceding::a[3]</value>
      <webElementGuid>45904e10-bc8a-4dd7-a1bb-5a8e2d5365fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AMOXICILLIN IFARS 500 MG BOX 10 STR @ 10 TABLokasi Rak: -'])[1]/preceding::a[3]</value>
      <webElementGuid>2401c66a-e8cf-49a2-8a25-e28d104a3b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>0b1782a2-9489-476e-a384-f008f404adf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/a</value>
      <webElementGuid>867cff61-5e87-4882-a5ab-877536a9f651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @title = 'Insert']</value>
      <webElementGuid>1bba0749-35c9-4ad9-b37a-a51522da1eee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
